### ISSUE TITLE
ble-serial script problem

### ISSUE THREAD

**Issue by rsostar** [Jakeler/ble-serial#1]
ble-scan works fine but when I try to run ble-scan -d xx:xx:xx..... it gives me the following
in <module>
      from ble_serial.fs_log import FS_log, Direction
  File "<fstring>", line 1
      (filename=)
                      ^
SyntaxError: invalid syntax

I have Python 3.7 on RPI4.

**Comment by Jakeler** [comment]
That is because I used a Python 3.8 feature there. Not really necessary, otherwise it should work with Python 3.6+, so I will change it.

**Comment by Jakeler** [comment]
New version 1.1.1 is up with the fix, please try it.
