### ISSUE TITLE
Does not work with nRF52DK(52832) + BLESerial/BLEPeripheral

### ISSUE THREAD

**Issue by yanbingyu07** [Jakeler/ble-serial#59]
I am using the Nordic dev board nRF52DK with nRF52832, using BLEPeripheral library. I can use mobile apps "nRF Connect" & "Bluefruit Connect" to connect to the nRF52DK. Then I want to use your python library on Win10, but it failed to connect. 

I saw another similar post about nRF52840, https://github.com/Jakeler/ble-serial/issues/48, but I tried the same parameters on command line, with the same failure. Can you please help? Thanks!

Here are the log messages:
```
C:\> ble-scan -d CD:8A:9F:72:4C:E7
...[deleted some lines, many bt devices nearby]

Started deep scan of CD:8A:9F:72:4C:E7
Found device CD:8A:9F:72:4C:E7: 2DA-BLE Port (out of 1)
SERVICE 00001800-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Access Profile
     CHARACTERISTIC 00002a00-0000-1000-8000-00805f9b34fb (Handle: 2):  ['read', 'write']
     CHARACTERISTIC 00002a01-0000-1000-8000-00805f9b34fb (Handle: 4):  ['read']
     CHARACTERISTIC 00002a04-0000-1000-8000-00805f9b34fb (Handle: 6):  ['read']
SERVICE 00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
     CHARACTERISTIC 00002a05-0000-1000-8000-00805f9b34fb (Handle: 9):  ['indicate']
         DESCRIPTOR 00002902-0000-1000-8000-00805f9b34fb (Handle: 11): Client Characteristic Configuration
SERVICE 6e400001-b5a3-f393-e0a9-e50e24dcca9e (Handle: 12): Nordic UART Service
     CHARACTERISTIC 6e400002-b5a3-f393-e0a9-e50e24dcca9e (Handle: 13): RX - Receive Data (Write) ['write-without-response']
         DESCRIPTOR 00002901-0000-1000-8000-00805f9b34fb (Handle: 15): Characteristic User Description
     CHARACTERISTIC 6e400003-b5a3-f393-e0a9-e50e24dcca9e (Handle: 16): TX - Transfer Data (Notify) ['notify']
         DESCRIPTOR 00002902-0000-1000-8000-00805f9b34fb (Handle: 18): Client Characteristic Configuration
         DESCRIPTOR 00002901-0000-1000-8000-00805f9b34fb (Handle: 19): Characteristic User Description

Completed deep scan of CD:8A:9F:72:4C:E7
Finished BLE scan

C:\> ble-serial -vv --dev 'CD:8A:9F:72:4C:E7' --read-uuid "6e400003-b5a3-f393-e0a9-e50e24dcca9e" --write-uuid "6e400002-b5a3-f393-e0a9-e50e24dcca9e" --timeout 10 --mtu 20 --port BLE
11:48:56.766 | DEBUG | main.py: Running: Namespace(adapter='hci0', addr_type='public', binlog=False, device='CD:8A:9F:72:4C:E7', filename=None, mode='rw', mtu=20, port='BLE', read_uuid='6e400003-b5a3-f393-e0a9-e50e24dcca9e', service_uuid=None, timeout=10.0, verbose=2, write_uuid='6e400002-b5a3-f393-e0a9-e50e24dcca9e')
11:48:56.766 | DEBUG | proactor_events.py: Using proactor: IocpProactor
11:48:56.769 | INFO | ble_interface.py: Receiver set up
11:48:57.066 | DEBUG | scanner.py: Received 02:90:58:1B:AB:7E: Unknown.
11:48:57.155 | DEBUG | scanner.py: Received 39:A6:FE:E1:BE:03: Unknown.
11:48:57.168 | DEBUG | scanner.py: Received 60:D2:B4:DD:31:15: Unknown.
11:48:57.175 | DEBUG | scanner.py: Received 60:D2:B4:DD:31:15: Unknown.
11:48:57.300 | DEBUG | scanner.py: Received CD:8A:9F:72:4C:E7: Unknown.
11:48:57.306 | DEBUG | scanner.py: 4 devices found. Watcher status: 3.
11:48:57.309 | INFO | ble_interface.py: Trying to connect with CD:8A:9F:72:4C:E7: Unknown
11:48:57.310 | DEBUG | client.py: Connecting to BLE device @ CD:8A:9F:72:4C:E7
11:48:57.448 | ERROR | main.py: Bluetooth connection failed: Failed to connect to 225995264249063. If the device requires pairing, then pair first. If the device uses a random address, it may have changed.
11:48:57.449 | WARNING | main.py: Shutdown initiated
11:48:57.450 | INFO | windows_com0com.py: Stopping RX+TX loop
11:48:57.451 | INFO | main.py: Shutdown complete.
```

**Setup:**
- OS: Windows 10
- Bluetooth Hardware: Intel Bluetooth, built-in laptop
- Python Version: 3.8.8
- ble-serial version: 2.6.0

**Comment by Jakeler** [comment]
The characteristics look correct, but the log indicates that it already fails before that - in the connection setup. So I would suspect some problem with the adapter, address or address type. 
```
If the device requires pairing, then pair first. If the device uses a random address, it may have changed.
```
Did you check this already?

Also you could try the service based device selection, it uses slightly different functions:
```
ble-serial -vv --service-uuid 6e400001-b5a3-f393-e0a9-e50e24dcca9e --read-uuid "6e400003-b5a3-f393-e0a9-e50e24dcca9e" --write-uuid "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
```
Otherwise please post the code you are using on dev board.

**Comment by yanbingyu07** [comment]
Jakeler,
Thanks for your responses. I have tried both of your suggestions already, both are still failed with same output.

The library code I am using are from BLEPeripheral: https://github.com/sandeepmistry/arduino-BLEPeripheral, it's example of BLESerial: https://github.com/sandeepmistry/arduino-BLEPeripheral/tree/master/examples/serial. The BLE-UART service can be accessed by mobile apps such as nRF-Connect and Bluefruit Connect. I'd like to access it from PC side using your library. 

Thanks for your help!

**Comment by yanbingyu07** [comment]
Jakeler,
Thanks for your help! Tried 1) specifying "--address_type=random" on command line; 2) installed your experimental-59-fix.zip. Still failed. Here are the output:
`
13:26:46.455 | DEBUG | main.py: Running: Namespace(adapter='hci0', addr_type='random', binlog=False, device='CD:8A:9F:72:4C:E7', filename=None, mode='rw', mtu=20, port='BLE', read_uuid='6e400003-b5a3-f393-e0a9-e50e24dcca9e', service_uuid=None, timeout=10.0, verbose=2, write_uuid='6e400002-b5a3-f393-e0a9-e50e24dcca9e')
ble-serial -vv --dev 'CD:8A:9F:72:4C:E7' --read-uuid "6e400003-b5a3-f393-e0a9-e50e24dcca9e" --write-uuid "6e400002-b5a3-f393-e0a9-e50e24dcca9e" --timeout 10 --mtu 20 --port BLE -a random
13:26:46.455 | DEBUG | proactor_events.py: Using proactor: IocpProactor
13:26:46.457 | INFO | ble_interface.py: Receiver set up
13:26:46.868 | DEBUG | scanner.py: Received CD:8A:9F:72:4C:E7: Unknown.
13:26:46.874 | DEBUG | scanner.py: 1 devices found. Watcher status: 3.
13:26:46.875 | INFO | ble_interface.py: Trying to connect with CD:8A:9F:72:4C:E7: Unknown
13:26:46.876 | DEBUG | client.py: Connecting to BLE device @ CD:8A:9F:72:4C:E7
13:26:47.341 | DEBUG | client.py: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x000001DE08923EF0>, error: 0, status: 1
13:26:47.342 | DEBUG | client.py: Get Services...
13:26:47.606 | DEBUG | client.py: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x000001DE08923F30>, error: 0, status: 0
13:26:47.606 | WARNING | ble_interface.py: Device CD:8A:9F:72:4C:E7 disconnected
13:26:47.606 | INFO | ble_interface.py: Stopping Bluetooth event loop
13:26:47.609 | ERROR | main.py: Bluetooth connection failed: Could not get GATT services: Unreachable
13:26:47.609 | WARNING | main.py: Shutdown initiated
13:26:47.609 | INFO | windows_com0com.py: Stopping RX+TX loop
13:26:47.610 | INFO | main.py: Shutdown complete.
`

BTW, now suddenly ble-scan deepscan does not work, got these output:
`
Started deep scan of CD:8A:9F:72:4C:E7
Found device CD:8A:9F:72:4C:E7: Feather nRF52832 Express (out of 1)
ERROR: Could not get GATT services: Unreachable
`

**Comment by yanbingyu07** [comment]
text formatting not as expected, used `Add code <>` to paste outputs.

**Comment by Jakeler** [comment]
You get the same log with 1) and 2) now? Can you somehow delete the device in windows settings and retry? 
The ticket does not specify the bleak version (`pip list`), but you could try the latest dev version:
```
pip install https://github.com/hbldh/bleak/archive/develop.zip
```
Otherwise I am running out of ideas now, as it already fails to connect. Starting to believe that it is some problem with the host machine or Windows. Any chance to try it on a different laptop, preferably with Linux?

btw: I fixed your formatting, surround code blocks by triple back ticks.

**Comment by yanbingyu07** [comment]
1. The error message were different, with "--address-type=random":
```
14:17:44.492 | DEBUG | client.py: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x00000213BDBF2F10>, error: 0, status: 1
14:17:44.493 | DEBUG | client.py: Get Services...
14:17:44.748 | DEBUG | client.py: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x00000213BDBF2F50>, error: 0, status: 0
14:17:44.748 | WARNING | ble_interface.py: Device CD:8A:9F:72:4C:E7 disconnected
14:17:44.748 | INFO | ble_interface.py: Stopping Bluetooth event loop
14:17:44.750 | ERROR | main.py: Bluetooth connection failed: Could not get GATT services: Unreachable
```
    without:
```
14:17:55.584 | ERROR | main.py: Bluetooth connection failed: Failed to connect to 225995264249063. If the device requires pairing, then pair first. If the device uses a random address, it may have changed.
```
2. Bleak was version 0.14.3, now after install, the new version is 0.15.0a1. both shows same results.
3. Learned a new trick on text formatting, thanks!
4. I will try a different PC.

**Comment by yanbingyu07** [comment]
Jakeler,
Good news! I tried on a different Laptop PC (Win11), it worked as expected. I have to use "--address-type random" option, otherwise it will not work.

There is a noticeable delay when transmitting from BLE board to the PC side. Any advice how to improve on it? The other direction seems ok.

What could be the cause on my previous PC, making it not working with your library?

Thank you very much!

**Comment by Jakeler** [comment]
Great! that is some progress. 
I don't really know why it does not work with the other PC though, can be anything from hardware to OS, drivers and configuration. Can only think of random trial and error. Do other apps with BLE devices function with it?

If I read the BLEPeripheral code correctly it does not immediately send, `write(uint8_t byte)` just puts it into a buffer. It is flushed to BLE in two cases: either [the buffer (20 bytes) is full](https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/0.4.0/examples/serial/BLESerial.cpp#L99) or [>100 ms passed since the last flush](https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/0.4.0/examples/serial/BLESerial.cpp#L33). Maybe you can optimize that.
