### ISSUE TITLE
MAC address is case sensitive

### ISSUE THREAD

**Issue by snhirsch** [Jakeler/ble-serial#95]
This one is simple, but caused some issues until I figured it out.  The ble-serial application does not work correctly when the alpha characters in the MAC address are passed in lower case.

**Comment by Jakeler** [comment]
Interesting, I just tested it on Linux and could not reproduce it: upper, lower and even mixed case all worked.
Assume it is WinRT specific, will test it on Windows 10/11 later. You use Windows 7 and the same software versions you mentioned in #94, right?

**Comment by snhirsch** [comment]
Yes, same environment as the other issue.

**Comment by Jakeler** [comment]
Still unconfirmed on W10, with Python 3.8, 3.10 and 3.12 it all worked. Same package versions.

Actually W7 is unsupported by the [bleak](https://github.com/hbldh/bleak) dependency:
> Supports Windows 10, version 16299 (Fall Creators Update) or greater

Idk how this can function [at all.](https://github.com/hbldh/bleak/issues/364) Though I don't have a W7 test system at hand.

**Comment by snhirsch** [comment]
Well, it is just a minor annoyance.  With full logging on I see a bunch of warnings about deprecated API usage that I believe comes from 'bleak'.  I can only assume they haven't yet pulled it completely.  Now I know never to update it!  

I'll close the issue.  Thanks again!
